# Generated by Django 4.1.1 on 2022-09-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_new_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descr',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='new_field',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio/images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
